# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: get img

on:
  schedule:
    - cron: '15 */3 * * *' # 毎3時間ごとに実行
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run get_img
      run: python get_img.py
    - name: Commit changes
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -u
          git add get/
          git diff-index --quiet HEAD || git commit -m "Get images"
          git push
